apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: demo-

resources:
  - server-deployment.yaml
  - server-service.yaml
  - server-headless-service.yaml
  - client-statefulset.yaml
  - client-headless-service.yaml
  - orch-statefulset.yaml
  - orch-headless-service.yaml
  - orch-service.yaml
  - serviceaccount.yaml

configurations:
  - namereferences.yaml