apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
  - name: grpc
    port: 50051
    targetPort: grpc
  - name: http
    port: 8080
    targetPort: http
  - name: tcp
    port: 9000
    targetPort: tcp
  - name: udp
    port: 9001
    protocol: UDP
    targetPort: udp
