apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
    app.kubernetes.io/component: workload
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: demo-server:latest
        imagePullPolicy: Always
        ports:
        - name: grpc
          containerPort: 50051
        - name: http
          containerPort: 8080
        - name: tcp
          containerPort: 9000
        - name: udp
          containerPort: 9001
          protocol: UDP

        # low resource requirements
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
          requests:
            memory: "32Mi"
            cpu: "100m"
      serviceAccountName: xdp-banner