// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.2
// source: orch/v1/agent/report/report.proto

package report

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Phase int32

const (
	Phase_Unknown Phase = 0
	Phase_Ready   Phase = 1
	Phase_Running Phase = 2
	Phase_Stopped Phase = 3
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "Unknown",
		1: "Ready",
		2: "Running",
		3: "Stopped",
	}
	Phase_value = map[string]int32{
		"Unknown": 0,
		"Ready":   1,
		"Running": 2,
		"Stopped": 3,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_orch_v1_agent_report_report_proto_enumTypes[0].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_orch_v1_agent_report_report_proto_enumTypes[0]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_orch_v1_agent_report_report_proto_rawDescGZIP(), []int{0}
}

type ErrorTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	RetryAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=retry_at,json=retryAt,proto3" json:"retry_at,omitempty"`
}

func (x *ErrorTime) Reset() {
	*x = ErrorTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orch_v1_agent_report_report_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorTime) ProtoMessage() {}

func (x *ErrorTime) ProtoReflect() protoreflect.Message {
	mi := &file_orch_v1_agent_report_report_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorTime.ProtoReflect.Descriptor instead.
func (*ErrorTime) Descriptor() ([]byte, []int) {
	return file_orch_v1_agent_report_report_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorTime) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorTime) GetRetryAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RetryAt
	}
	return nil
}

// Request for reporting the status of an agent
type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GrpcEndpoint string     `protobuf:"bytes,2,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	ConfigName   string     `protobuf:"bytes,3,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	Phase        Phase      `protobuf:"varint,4,opt,name=phase,proto3,enum=agent.reoprt.Phase" json:"phase,omitempty"`
	Error        *ErrorTime `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orch_v1_agent_report_report_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_orch_v1_agent_report_report_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_orch_v1_agent_report_report_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Status) GetGrpcEndpoint() string {
	if x != nil {
		return x.GrpcEndpoint
	}
	return ""
}

func (x *Status) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *Status) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_Unknown
}

func (x *Status) GetError() *ErrorTime {
	if x != nil {
		return x.Error
	}
	return nil
}

type ReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orch_v1_agent_report_report_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orch_v1_agent_report_report_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_orch_v1_agent_report_report_proto_rawDescGZIP(), []int{2}
}

var File_orch_v1_agent_report_report_proto protoreflect.FileDescriptor

var file_orch_v1_agent_report_report_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6f, 0x72, 0x63, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f,
	0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x72, 0x65, 0x6f, 0x70, 0x72,
	0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x72, 0x65, 0x74,
	0x72, 0x79, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x72, 0x65, 0x74, 0x72, 0x79, 0x41, 0x74,
	0x22, 0xbc, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x67, 0x72, 0x70, 0x63, 0x45, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x72, 0x65, 0x6f,
	0x70, 0x72, 0x74, 0x2e, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65,
	0x12, 0x2d, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x72, 0x65, 0x6f, 0x70, 0x72, 0x74, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x10, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2a, 0x39, 0x0a, 0x05, 0x50, 0x68, 0x61, 0x73, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e,
	0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x65, 0x61, 0x64, 0x79,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x10, 0x03, 0x32, 0x4d, 0x0a, 0x0d,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a,
	0x06, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x72, 0x65, 0x6f, 0x70, 0x72, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x1c, 0x2e,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x72, 0x65, 0x6f, 0x70, 0x72, 0x74, 0x2e, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x16, 0x5a, 0x14, 0x6f,
	0x72, 0x63, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x72, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orch_v1_agent_report_report_proto_rawDescOnce sync.Once
	file_orch_v1_agent_report_report_proto_rawDescData = file_orch_v1_agent_report_report_proto_rawDesc
)

func file_orch_v1_agent_report_report_proto_rawDescGZIP() []byte {
	file_orch_v1_agent_report_report_proto_rawDescOnce.Do(func() {
		file_orch_v1_agent_report_report_proto_rawDescData = protoimpl.X.CompressGZIP(file_orch_v1_agent_report_report_proto_rawDescData)
	})
	return file_orch_v1_agent_report_report_proto_rawDescData
}

var file_orch_v1_agent_report_report_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_orch_v1_agent_report_report_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_orch_v1_agent_report_report_proto_goTypes = []any{
	(Phase)(0),                    // 0: agent.reoprt.Phase
	(*ErrorTime)(nil),             // 1: agent.reoprt.ErrorTime
	(*Status)(nil),                // 2: agent.reoprt.Status
	(*ReportResponse)(nil),        // 3: agent.reoprt.ReportResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_orch_v1_agent_report_report_proto_depIdxs = []int32{
	4, // 0: agent.reoprt.ErrorTime.retry_at:type_name -> google.protobuf.Timestamp
	0, // 1: agent.reoprt.Status.phase:type_name -> agent.reoprt.Phase
	1, // 2: agent.reoprt.Status.error:type_name -> agent.reoprt.ErrorTime
	2, // 3: agent.reoprt.ReportService.Report:input_type -> agent.reoprt.Status
	3, // 4: agent.reoprt.ReportService.Report:output_type -> agent.reoprt.ReportResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_orch_v1_agent_report_report_proto_init() }
func file_orch_v1_agent_report_report_proto_init() {
	if File_orch_v1_agent_report_report_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_orch_v1_agent_report_report_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ErrorTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orch_v1_agent_report_report_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orch_v1_agent_report_report_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orch_v1_agent_report_report_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orch_v1_agent_report_report_proto_goTypes,
		DependencyIndexes: file_orch_v1_agent_report_report_proto_depIdxs,
		EnumInfos:         file_orch_v1_agent_report_report_proto_enumTypes,
		MessageInfos:      file_orch_v1_agent_report_report_proto_msgTypes,
	}.Build()
	File_orch_v1_agent_report_report_proto = out.File
	file_orch_v1_agent_report_report_proto_rawDesc = nil
	file_orch_v1_agent_report_report_proto_goTypes = nil
	file_orch_v1_agent_report_report_proto_depIdxs = nil
}
