// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.2
// source: orch/v1/orch/orch.proto

package orch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // name of the orch
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orch_v1_orch_orch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orch_v1_orch_orch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_orch_v1_orch_orch_proto_rawDescGZIP(), []int{0}
}

func (x *GetInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *structpb.Struct `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"` // info of the orch
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orch_v1_orch_orch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orch_v1_orch_orch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_orch_v1_orch_orch_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetInfo() *structpb.Struct {
	if x != nil {
		return x.Info
	}
	return nil
}

type ListInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagesize int64  `protobuf:"varint,1,opt,name=pagesize,proto3" json:"pagesize,omitempty"` // number of info per page
	Cursor   string `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`      // cursor for pagination
}

func (x *ListInfoRequest) Reset() {
	*x = ListInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orch_v1_orch_orch_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInfoRequest) ProtoMessage() {}

func (x *ListInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orch_v1_orch_orch_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInfoRequest.ProtoReflect.Descriptor instead.
func (*ListInfoRequest) Descriptor() ([]byte, []int) {
	return file_orch_v1_orch_orch_proto_rawDescGZIP(), []int{2}
}

func (x *ListInfoRequest) GetPagesize() int64 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

func (x *ListInfoRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total       int64                       `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`                                                                                        // total number of agents
	TotalPage   int64                       `protobuf:"varint,2,opt,name=totalPage,proto3" json:"totalPage,omitempty"`                                                                                // total number of pages
	CurrentPage int64                       `protobuf:"varint,3,opt,name=currentPage,proto3" json:"currentPage,omitempty"`                                                                            // current page
	HasNext     bool                        `protobuf:"varint,4,opt,name=hasNext,proto3" json:"hasNext,omitempty"`                                                                                    // has next page
	NextCursor  string                      `protobuf:"bytes,5,opt,name=nextCursor,proto3" json:"nextCursor,omitempty"`                                                                               // cursor for next page
	Items       map[string]*structpb.Struct `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // list of info with name as key
}

func (x *ListInfoResponse) Reset() {
	*x = ListInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orch_v1_orch_orch_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInfoResponse) ProtoMessage() {}

func (x *ListInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orch_v1_orch_orch_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInfoResponse.ProtoReflect.Descriptor instead.
func (*ListInfoResponse) Descriptor() ([]byte, []int) {
	return file_orch_v1_orch_orch_proto_rawDescGZIP(), []int{3}
}

func (x *ListInfoResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListInfoResponse) GetTotalPage() int64 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *ListInfoResponse) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ListInfoResponse) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *ListInfoResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListInfoResponse) GetItems() map[string]*structpb.Struct {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_orch_v1_orch_orch_proto protoreflect.FileDescriptor

var file_orch_v1_orch_orch_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6f, 0x72, 0x63, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x72, 0x63, 0x68, 0x2f, 0x6f,
	0x72, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6f, 0x72, 0x63, 0x68, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x3e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x22, 0x45, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69,
	0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x22, 0xae, 0x02, 0x0a, 0x10, 0x4c,
	0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50,
	0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x4e, 0x65, 0x78, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4e, 0x65, 0x78, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12,
	0x37, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x6f, 0x72, 0x63, 0x68, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x51, 0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0x80, 0x01, 0x0a, 0x0b,
	0x4f, 0x72, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x2e, 0x6f, 0x72, 0x63, 0x68, 0x2e, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6f,
	0x72, 0x63, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x15, 0x2e, 0x6f, 0x72, 0x63, 0x68, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6f, 0x72, 0x63, 0x68, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e,
	0x5a, 0x0c, 0x6f, 0x72, 0x63, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x72, 0x63, 0x68, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orch_v1_orch_orch_proto_rawDescOnce sync.Once
	file_orch_v1_orch_orch_proto_rawDescData = file_orch_v1_orch_orch_proto_rawDesc
)

func file_orch_v1_orch_orch_proto_rawDescGZIP() []byte {
	file_orch_v1_orch_orch_proto_rawDescOnce.Do(func() {
		file_orch_v1_orch_orch_proto_rawDescData = protoimpl.X.CompressGZIP(file_orch_v1_orch_orch_proto_rawDescData)
	})
	return file_orch_v1_orch_orch_proto_rawDescData
}

var file_orch_v1_orch_orch_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_orch_v1_orch_orch_proto_goTypes = []any{
	(*GetInfoRequest)(nil),   // 0: orch.GetInfoRequest
	(*GetInfoResponse)(nil),  // 1: orch.GetInfoResponse
	(*ListInfoRequest)(nil),  // 2: orch.ListInfoRequest
	(*ListInfoResponse)(nil), // 3: orch.ListInfoResponse
	nil,                      // 4: orch.ListInfoResponse.ItemsEntry
	(*structpb.Struct)(nil),  // 5: google.protobuf.Struct
}
var file_orch_v1_orch_orch_proto_depIdxs = []int32{
	5, // 0: orch.GetInfoResponse.info:type_name -> google.protobuf.Struct
	4, // 1: orch.ListInfoResponse.items:type_name -> orch.ListInfoResponse.ItemsEntry
	5, // 2: orch.ListInfoResponse.ItemsEntry.value:type_name -> google.protobuf.Struct
	0, // 3: orch.OrchService.GetInfo:input_type -> orch.GetInfoRequest
	2, // 4: orch.OrchService.ListInfo:input_type -> orch.ListInfoRequest
	1, // 5: orch.OrchService.GetInfo:output_type -> orch.GetInfoResponse
	3, // 6: orch.OrchService.ListInfo:output_type -> orch.ListInfoResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_orch_v1_orch_orch_proto_init() }
func file_orch_v1_orch_orch_proto_init() {
	if File_orch_v1_orch_orch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_orch_v1_orch_orch_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orch_v1_orch_orch_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orch_v1_orch_orch_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orch_v1_orch_orch_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ListInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orch_v1_orch_orch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orch_v1_orch_orch_proto_goTypes,
		DependencyIndexes: file_orch_v1_orch_orch_proto_depIdxs,
		MessageInfos:      file_orch_v1_orch_orch_proto_msgTypes,
	}.Build()
	File_orch_v1_orch_orch_proto = out.File
	file_orch_v1_orch_orch_proto_rawDesc = nil
	file_orch_v1_orch_orch_proto_goTypes = nil
	file_orch_v1_orch_orch_proto_depIdxs = nil
}
